import type { Castle, PiecePosition } from './types'

const GOTE_STANDARD: PiecePosition[] = [
  { kanji: '香', col: 9, row: 1, isGote: true },
  { kanji: '桂', col: 8, row: 1, isGote: true },
  { kanji: '銀', col: 7, row: 1, isGote: true },
  { kanji: '金', col: 6, row: 1, isGote: true },
  { kanji: '玉', col: 5, row: 1, isGote: true },
  { kanji: '金', col: 4, row: 1, isGote: true },
  { kanji: '銀', col: 3, row: 1, isGote: true },
  { kanji: '桂', col: 2, row: 1, isGote: true },
  { kanji: '香', col: 1, row: 1, isGote: true },
  { kanji: '飛', col: 8, row: 2, isGote: true },
  { kanji: '角', col: 2, row: 2, isGote: true },
  ...Array.from({ length: 9 }, (_, i): PiecePosition => ({
    kanji: '歩', col: 9 - i, row: 3, isGote: true,
  })),
]

const MINO_PIECES: PiecePosition[] = [
  ...GOTE_STANDARD,
  { kanji: '歩', col: 9, row: 7, isGote: false },
  { kanji: '銀', col: 7, row: 7, isGote: false },
  { kanji: '歩', col: 5, row: 7, isGote: false },
  { kanji: '歩', col: 4, row: 7, isGote: false },
  { kanji: '角', col: 3, row: 7, isGote: false },
  { kanji: '歩', col: 2, row: 7, isGote: false },
  { kanji: '歩', col: 1, row: 7, isGote: false },
  { kanji: '飛', col: 9, row: 8, isGote: false },
  { kanji: '玉', col: 8, row: 8, isGote: false },
  { kanji: '金', col: 7, row: 8, isGote: false },
  { kanji: '香', col: 9, row: 9, isGote: false },
  { kanji: '桂', col: 8, row: 9, isGote: false },
  { kanji: '金', col: 6, row: 9, isGote: false },
  { kanji: '金', col: 4, row: 9, isGote: false },
  { kanji: '桂', col: 2, row: 9, isGote: false },
  { kanji: '香', col: 1, row: 9, isGote: false },
]

const MINO_GUIDE_PIECES: PiecePosition[] = [
  ...GOTE_STANDARD,
  { kanji: '歩', col: 9, row: 7, isGote: false },
  { kanji: '歩', col: 5, row: 7, isGote: false },
  { kanji: '歩', col: 4, row: 7, isGote: false },
  { kanji: '角', col: 3, row: 7, isGote: false },
  { kanji: '歩', col: 2, row: 7, isGote: false },
  { kanji: '歩', col: 1, row: 7, isGote: false },
  { kanji: '飛', col: 9, row: 8, isGote: false },
  { kanji: '玉', col: 8, row: 8, isGote: false },
  { kanji: '金', col: 6, row: 8, isGote: false },
  { kanji: '香', col: 9, row: 9, isGote: false },
  { kanji: '桂', col: 8, row: 9, isGote: false },
  { kanji: '銀', col: 7, row: 9, isGote: false },
  { kanji: '金', col: 4, row: 9, isGote: false },
  { kanji: '桂', col: 2, row: 9, isGote: false },
  { kanji: '香', col: 1, row: 9, isGote: false },
]

const MINO_TEST_PIECES: PiecePosition[] = [
  { kanji: '玉', col: 5, row: 1, isGote: true },
  { kanji: '金', col: 4, row: 1, isGote: true },
  { kanji: '金', col: 6, row: 1, isGote: true },
  { kanji: '銀', col: 3, row: 2, isGote: true },
  { kanji: '飛', col: 3, row: 3, isGote: true },
  { kanji: '角', col: 7, row: 4, isGote: true },
  { kanji: '歩', col: 9, row: 3, isGote: true },
  { kanji: '歩', col: 8, row: 3, isGote: true },
  { kanji: '歩', col: 5, row: 3, isGote: true },
  { kanji: '歩', col: 4, row: 4, isGote: true },
  { kanji: '歩', col: 2, row: 3, isGote: true },
  { kanji: '歩', col: 1, row: 3, isGote: true },
  { kanji: '歩', col: 9, row: 7, isGote: false },
  { kanji: '歩', col: 8, row: 6, isGote: false },
  { kanji: '銀', col: 6, row: 7, isGote: false },
  { kanji: '歩', col: 4, row: 7, isGote: false },
  { kanji: '歩', col: 2, row: 7, isGote: false },
  { kanji: '歩', col: 1, row: 7, isGote: false },
  { kanji: '飛', col: 4, row: 8, isGote: false },
  { kanji: '玉', col: 8, row: 8, isGote: false },
  { kanji: '金', col: 7, row: 8, isGote: false },
  { kanji: '金', col: 5, row: 8, isGote: false },
  { kanji: '香', col: 9, row: 9, isGote: false },
  { kanji: '桂', col: 8, row: 9, isGote: false },
  { kanji: '金', col: 6, row: 9, isGote: false },
  { kanji: '桂', col: 2, row: 9, isGote: false },
  { kanji: '香', col: 1, row: 9, isGote: false },
]

const SIMPLE_CASTLE_PIECES = (kingCol: number, goldCol: number, silverCol: number, rookCol: number): PiecePosition[] => [
  ...GOTE_STANDARD,
  { kanji: '歩', col: 9, row: 7, isGote: false },
  { kanji: '銀', col: silverCol, row: 7, isGote: false },
  { kanji: '歩', col: 5, row: 7, isGote: false },
  { kanji: '歩', col: 4, row: 7, isGote: false },
  { kanji: '歩', col: 2, row: 7, isGote: false },
  { kanji: '歩', col: 1, row: 7, isGote: false },
  { kanji: '飛', col: rookCol, row: 8, isGote: false },
  { kanji: '玉', col: kingCol, row: 8, isGote: false },
  { kanji: '金', col: goldCol, row: 8, isGote: false },
  { kanji: '香', col: 9, row: 9, isGote: false },
  { kanji: '桂', col: 8, row: 9, isGote: false },
  { kanji: '金', col: 6, row: 9, isGote: false },
  { kanji: '桂', col: 2, row: 9, isGote: false },
  { kanji: '香', col: 1, row: 9, isGote: false },
]

// 矢倉 pieces (居飛車, king goes right)
const YAGURA_PIECES: PiecePosition[] = [
  ...GOTE_STANDARD,
  { kanji: '歩', col: 9, row: 7, isGote: false },
  { kanji: '銀', col: 7, row: 7, isGote: false },
  { kanji: '銀', col: 6, row: 7, isGote: false },
  { kanji: '歩', col: 5, row: 7, isGote: false },
  { kanji: '歩', col: 4, row: 7, isGote: false },
  { kanji: '歩', col: 2, row: 7, isGote: false },
  { kanji: '歩', col: 1, row: 7, isGote: false },
  { kanji: '角', col: 8, row: 8, isGote: false },
  { kanji: '玉', col: 6, row: 8, isGote: false },
  { kanji: '金', col: 7, row: 8, isGote: false },
  { kanji: '金', col: 5, row: 8, isGote: false },
  { kanji: '香', col: 9, row: 9, isGote: false },
  { kanji: '桂', col: 8, row: 9, isGote: false },
  { kanji: '飛', col: 2, row: 8, isGote: false },
  { kanji: '桂', col: 2, row: 9, isGote: false },
  { kanji: '香', col: 1, row: 9, isGote: false },
]

export const CASTLES: Castle[] = [
  {
    id: 'mino',
    name: '美濃囲い',
    type: 'furibisha',
    difficulty: 'easy',
    tags: ['居飛車向き'],
    description: [
      'バランスが良く扱いやすい',
      '受けが強く持久戦に強い',
      '初心者におすすめの基本形',
    ],
    features: [
      'バランスが良く扱いやすい',
      '受けが強く持久戦に強い',
      '初心者におすすめの基本形',
    ],
    weaknesses: [
      '端を攻められると弱い',
      '急戦にはやや弱い',
      '攻めがやや受け身になりやすい',
    ],
    recommendedAgainst: '居飛車党全般に有効\n特に振り飛車に強い',
    basicSteps: [
      '▲7六歩',
      '▲7八飛',
      '▲6八銀',
      '▲4八玉',
      '▲3八玉',
      '▲7八銀',
    ],
    pieces: MINO_PIECES,
    guidePieces: MINO_GUIDE_PIECES,
    guideSteps: [
      { move: '▲7八銀', hint: '銀を7八に上げて玉の斜め前を守ります。美濃囲いの要の一手です。', highlight: { col: 7, row: 8 } },
      { move: '▲7七銀', hint: 'さらに銀を7七に上げて美濃の形に近づけます。銀が玉を斜め上から守ります。', highlight: { col: 7, row: 7 } },
      { move: '▲6七金右', hint: '右の金を6七に上げます。金銀が連携して玉を守る形を作ります。', highlight: { col: 6, row: 7 } },
      { move: '▲5八金左', hint: '左の金も5八に引き付けます。二枚の金で玉の前面を守ります。', highlight: { col: 5, row: 8 } },
      { move: '▲9八香', hint: '端の香車を9八に上げて端の守りを固めます。', highlight: { col: 9, row: 8 } },
      { move: '▲8八玉', hint: '玉を8八に落ち着かせます。金銀に守られた安全地帯——美濃囲いの完成です！', highlight: { col: 8, row: 8 } },
    ],
    guideHighlight: { col: 7, row: 8 },
    guideNextMove: '▲7八銀',
    guideStep: [6, 10],
    guideProgress: 60,
    testPieces: MINO_TEST_PIECES,
    testScore: 85,
    testMessage: 'あと少しで完成！',
    testGoodPoints: [
      '玉の囲いを完成に近い',
      '金銀の配置が良い',
      '左辺の受けが整っている',
    ],
    testFixPoints: [
      '右銀を六にあがろう',
      '飛車の位置が課題',
      '桂馬の活用を考えよう',
    ],
  },
  {
    id: 'takamino',
    name: '高美濃',
    type: 'furibisha',
    difficulty: 'medium',
    tags: ['居飛車向き'],
    description: [
      '美濃囲いをさらに発展させた形',
      '玉の囲いがより堅固',
      'しっかり捌きたい人に向く',
    ],
    features: ['美濃囲いよりさらに堅い', '端攻めへの耐性が高い', '持久戦に強い'],
    weaknesses: ['組むのに手数がかかる', '急戦に対応しにくい'],
    recommendedAgainst: '持久戦志向の居飛車党',
    basicSteps: ['▲7六歩', '▲6八玉', '▲7八玉', '▲8八玉', '▲7八銀', '▲7七銀'],
    pieces: SIMPLE_CASTLE_PIECES(8, 7, 7, 9),
    guidePieces: SIMPLE_CASTLE_PIECES(8, 6, 7, 9),
    guideSteps: [
      { move: '▲7八銀', hint: '銀を7八に上げます。美濃から高美濃へ発展する第一歩。', highlight: { col: 7, row: 8 } },
      { move: '▲8七銀', hint: '銀をさらに8七に上げます。高美濃の特徴的な形になります。', highlight: { col: 8, row: 7 } },
      { move: '▲6七金右', hint: '右の金を6七に上げて守りを厚くします。', highlight: { col: 6, row: 7 } },
      { move: '▲7九金左', hint: '左の金を7九に引き付けます。', highlight: { col: 7, row: 9 } },
      { move: '▲9八香', hint: '端の香車を9八に上げて端の守りを固めます。', highlight: { col: 9, row: 8 } },
      { move: '▲8八玉', hint: '玉を8八に収めます。銀冠に守られた高美濃囲いの完成です！', highlight: { col: 8, row: 8 } },
    ],
    guideHighlight: { col: 7, row: 8 },
    guideNextMove: '▲7八銀',
    guideStep: [5, 8],
    guideProgress: 62,
    testPieces: MINO_TEST_PIECES,
    testScore: 80,
    testMessage: 'もう少し！',
    testGoodPoints: ['玉の位置が正しい', '金の配置が良い'],
    testFixPoints: ['銀をもう一段上げよう'],
  },
  {
    id: 'ginkan',
    name: '銀冠',
    type: 'ibisha',
    difficulty: 'medium',
    tags: ['居飛車向き'],
    description: [
      '銀で玉を囲うコンパクトな囲い',
      '攻守のバランスが良い',
      '急戦にも対応しやすい',
    ],
    features: ['攻守バランスが良い', '組みやすい', '相手を選ばない'],
    weaknesses: ['銀が守りに固定される', '端攻めが有効'],
    recommendedAgainst: '居飛車・振り飛車どちらにも',
    basicSteps: ['▲7六歩', '▲6八銀', '▲5七銀', '▲4八玉', '▲3八玉', '▲2八玉'],
    pieces: SIMPLE_CASTLE_PIECES(7, 6, 6, 9),
    guidePieces: SIMPLE_CASTLE_PIECES(7, 7, 6, 9),
    guideSteps: [
      { move: '▲6八銀', hint: '銀を6八に上げます。玉の移動への準備です。', highlight: { col: 6, row: 8 } },
      { move: '▲5七銀', hint: '銀をさらに5七に上げます。中央付近での銀の活用。', highlight: { col: 5, row: 7 } },
      { move: '▲4八玉', hint: '玉を4八に移動します。銀の守りに向かって動き始めます。', highlight: { col: 4, row: 8 } },
      { move: '▲3八玉', hint: '玉を3八にさらに引きます。', highlight: { col: 3, row: 8 } },
      { move: '▲2八玉', hint: '玉を2八まで寄せます。', highlight: { col: 2, row: 8 } },
      { move: '▲3七銀', hint: '銀を3七に戻して玉の頭を守ります。銀冠囲いの完成です！', highlight: { col: 3, row: 7 } },
    ],
    guideHighlight: { col: 6, row: 8 },
    guideNextMove: '▲6八銀',
    guideStep: [4, 8],
    guideProgress: 50,
    testPieces: MINO_TEST_PIECES,
    testScore: 75,
    testMessage: 'あともう一息！',
    testGoodPoints: ['銀の位置が合っている'],
    testFixPoints: ['玉をもう少し右に', '金の配置を調整'],
  },
  {
    id: 'yagura',
    name: '矢倉囲い',
    type: 'ibisha',
    difficulty: 'hard',
    tags: ['居飛車向き'],
    description: [
      '居飛車の最も堅い囲いの一つ',
      '高段者で高い採用率',
      '囲いの理解が重要',
    ],
    features: ['非常に堅固', '持久戦に圧倒的に強い', '金銀4枚の強固な守り'],
    weaknesses: ['組むのに多くの手数', '急戦に崩されることも'],
    recommendedAgainst: '相居飛車（矢倉戦）',
    basicSteps: ['▲7六歩', '▲6八銀', '▲7七銀', '▲6九玉', '▲7九玉', '▲6八金'],
    pieces: YAGURA_PIECES,
    guidePieces: SIMPLE_CASTLE_PIECES(6, 7, 7, 2),
    guideSteps: [
      { move: '▲6八銀', hint: '銀を6八に上げます。矢倉への準備の第一歩。', highlight: { col: 6, row: 8 } },
      { move: '▲7七銀', hint: '銀を7七に上げます。飛車先の歩を銀で守る重要な一手。', highlight: { col: 7, row: 7 } },
      { move: '▲6九玉', hint: '玉を6九に移動します。矢倉囲いへ向けて玉が動き始めます。', highlight: { col: 6, row: 9 } },
      { move: '▲7九玉', hint: '玉を7九に移動。銀の守りに近付きます。', highlight: { col: 7, row: 9 } },
      { move: '▲7八金右', hint: '右の金を7八に上げます。玉の前面を守ります。', highlight: { col: 7, row: 8 } },
      { move: '▲6八金左', hint: '左の金も6八に引き付けます。金二枚で玉を護衛。', highlight: { col: 6, row: 8 } },
      { move: '▲6七銀右', hint: '銀を6七に引き上げて守りを整えます。', highlight: { col: 6, row: 7 } },
      { move: '▲7八銀', hint: '最後に銀を7八に配置。金銀4枚の矢倉囲いが完成です！', highlight: { col: 7, row: 8 } },
    ],
    guideHighlight: { col: 6, row: 8 },
    guideNextMove: '▲6八玉',
    guideStep: [7, 12],
    guideProgress: 58,
    testPieces: MINO_TEST_PIECES,
    testScore: 70,
    testMessage: 'もう少し頑張ろう！',
    testGoodPoints: ['銀の配置が正しい'],
    testFixPoints: ['玉をさらに移動', '金を上に上げよう', '角の使い方を工夫'],
  },
  {
    id: 'fune',
    name: '舟囲い',
    type: 'ibisha',
    difficulty: 'medium',
    tags: ['居飛車向き'],
    description: [
      '玉を守る囲みのない囲い',
      '相手の攻めに合わせやすい',
      '六角の駒の展開を抑える',
    ],
    features: ['素早く組める', '攻撃的な構え', '柔軟な対応が可能'],
    weaknesses: ['守りが薄い', '持久戦には向かない'],
    recommendedAgainst: '速攻志向の相手',
    basicSteps: ['▲7六歩', '▲6八玉', '▲7八玉', '▲5八金右', '▲4八銀', '▲3八銀'],
    pieces: SIMPLE_CASTLE_PIECES(7, 6, 7, 2),
    guidePieces: SIMPLE_CASTLE_PIECES(7, 7, 7, 2),
    guideSteps: [
      { move: '▲6八玉', hint: '玉を6八に移動します。舟囲いは素早く組めるのが特長。', highlight: { col: 6, row: 8 } },
      { move: '▲7八玉', hint: '玉を7八に引き付けます。', highlight: { col: 7, row: 8 } },
      { move: '▲5八金右', hint: '右の金を5八に上げます。玉の横を守ります。', highlight: { col: 5, row: 8 } },
      { move: '▲4八銀', hint: '銀を4八に上げます。', highlight: { col: 4, row: 8 } },
      { move: '▲3八銀', hint: '銀を3八に引き付けて完成。素早く組めるのが舟囲いの魅力です！', highlight: { col: 3, row: 8 } },
    ],
    guideHighlight: { col: 6, row: 8 },
    guideNextMove: '▲6八金',
    guideStep: [3, 7],
    guideProgress: 43,
    testPieces: MINO_TEST_PIECES,
    testScore: 78,
    testMessage: 'いい感じ！',
    testGoodPoints: ['玉の位置が正しい'],
    testFixPoints: ['金をもう少し上に'],
  },
  {
    id: 'ibisha-anaguma',
    name: '居飛車穴熊',
    type: 'ibisha',
    difficulty: 'hard',
    tags: ['居飛車向き'],
    description: [
      '最も堅固な囲いの一つ',
      '守りを固めて攻撃を狙う',
      '上級者向けの戦法',
    ],
    features: ['圧倒的な堅さ', '持久戦最強クラス', '玉が安全'],
    weaknesses: ['組むのが難しい', '攻めへの転換に手数', '端攻めに注意'],
    recommendedAgainst: '振り飛車党（対振り飛車で多用）',
    basicSteps: ['▲7六歩', '▲6八玉', '▲7八玉', '▲8八玉', '▲9八玉', '▲8八銀'],
    pieces: SIMPLE_CASTLE_PIECES(9, 8, 8, 2),
    guidePieces: SIMPLE_CASTLE_PIECES(9, 9, 8, 2),
    guideSteps: [
      { move: '▲6八玉', hint: '玉を6八に移動します。端への長い旅が始まります。', highlight: { col: 6, row: 8 } },
      { move: '▲7八玉', hint: '玉を7八に移動。端に向かって一歩一歩。', highlight: { col: 7, row: 8 } },
      { move: '▲8八玉', hint: '玉を8八に移動。穴熊への道。', highlight: { col: 8, row: 8 } },
      { move: '▲9八玉', hint: '玉を9八まで寄せます。端への一手。', highlight: { col: 9, row: 8 } },
      { move: '▲9九玉', hint: '玉を9九の隅に収めます。これが穴熊の「穴」です。', highlight: { col: 9, row: 9 } },
      { move: '▲8八銀', hint: '銀を8八に上げて玉の斜め上を守ります。', highlight: { col: 8, row: 8 } },
      { move: '▲7九金', hint: '金を7九に引き付けます。', highlight: { col: 7, row: 9 } },
      { move: '▲8九金', hint: '金を8九に配置。玉を三方から守る居飛車穴熊の完成です！', highlight: { col: 8, row: 9 } },
    ],
    guideHighlight: { col: 9, row: 8 },
    guideNextMove: '▲9八玉',
    guideStep: [8, 14],
    guideProgress: 57,
    testPieces: MINO_TEST_PIECES,
    testScore: 72,
    testMessage: 'あともう少し！',
    testGoodPoints: ['金銀の形が良い'],
    testFixPoints: ['玉をもっと端に', '上部補強が必要'],
  },
  {
    id: 'furibisha-anaguma',
    name: '振り飛車穴熊',
    type: 'furibisha',
    difficulty: 'hard',
    tags: ['振り飛車向き'],
    description: [
      '振り飛車の最強囲い',
      '玉を遠く囲って戦う',
      '受けの強さは抜群',
    ],
    features: ['振り飛車最強の守り', '長期戦で力を発揮', '相手に主導権を与えない'],
    weaknesses: ['組むのが長い', '端攻めを食らいやすい', '攻めの駒が使いにくい'],
    recommendedAgainst: '居飛車党（相穴熊も含む）',
    basicSteps: ['▲7六歩', '▲7八飛', '▲6八銀', '▲5八金', '▲4八玉', '▲3八玉'],
    pieces: SIMPLE_CASTLE_PIECES(1, 2, 2, 7),
    guidePieces: SIMPLE_CASTLE_PIECES(1, 1, 2, 7),
    guideSteps: [
      { move: '▲7八飛', hint: '飛車を7筋に振ります。振り飛車の出発点です。', highlight: { col: 7, row: 8 } },
      { move: '▲4八玉', hint: '玉を4八に移動。端への長い旅の始まりです。', highlight: { col: 4, row: 8 } },
      { move: '▲3八玉', hint: '玉を3八にさらに移動。', highlight: { col: 3, row: 8 } },
      { move: '▲2八玉', hint: '玉を2八に移動。', highlight: { col: 2, row: 8 } },
      { move: '▲1八玉', hint: '玉を1八の端に収めます。', highlight: { col: 1, row: 8 } },
      { move: '▲1九玉', hint: '玉を1九の隅に。振り飛車穴熊の「穴」です。', highlight: { col: 1, row: 9 } },
      { move: '▲2八銀', hint: '銀を2八に上げて玉を守ります。', highlight: { col: 2, row: 8 } },
      { move: '▲2九金', hint: '金を2九に配置。玉を三方から守る振り飛車穴熊の完成です！', highlight: { col: 2, row: 9 } },
    ],
    guideHighlight: { col: 1, row: 8 },
    guideNextMove: '▲1八玉',
    guideStep: [6, 12],
    guideProgress: 50,
    testPieces: MINO_TEST_PIECES,
    testScore: 68,
    testMessage: 'もう少し頑張ろう！',
    testGoodPoints: ['飛車の位置が良い'],
    testFixPoints: ['玉をもっと端に移動', '銀金の配置を整えよう'],
  },
]

export function getCastle(id: string): Castle | undefined {
  return CASTLES.find(c => c.id === id)
}
