import type { Castle, PiecePosition } from './types'

const GOTE_STANDARD: PiecePosition[] = [
  { kanji: '香', col: 9, row: 1, isGote: true },
  { kanji: '桂', col: 8, row: 1, isGote: true },
  { kanji: '銀', col: 7, row: 1, isGote: true },
  { kanji: '金', col: 6, row: 1, isGote: true },
  { kanji: '玉', col: 5, row: 1, isGote: true },
  { kanji: '金', col: 4, row: 1, isGote: true },
  { kanji: '銀', col: 3, row: 1, isGote: true },
  { kanji: '桂', col: 2, row: 1, isGote: true },
  { kanji: '香', col: 1, row: 1, isGote: true },
  { kanji: '飛', col: 8, row: 2, isGote: true },
  { kanji: '角', col: 2, row: 2, isGote: true },
  ...Array.from({ length: 9 }, (_, i): PiecePosition => ({
    kanji: '歩', col: 9 - i, row: 3, isGote: true,
  })),
]

const MINO_PIECES: PiecePosition[] = [
  ...GOTE_STANDARD,
  { kanji: '歩', col: 9, row: 7, isGote: false },
  { kanji: '銀', col: 7, row: 7, isGote: false },
  { kanji: '歩', col: 5, row: 7, isGote: false },
  { kanji: '歩', col: 4, row: 7, isGote: false },
  { kanji: '角', col: 3, row: 7, isGote: false },
  { kanji: '歩', col: 2, row: 7, isGote: false },
  { kanji: '歩', col: 1, row: 7, isGote: false },
  { kanji: '飛', col: 9, row: 8, isGote: false },
  { kanji: '玉', col: 8, row: 8, isGote: false },
  { kanji: '金', col: 7, row: 8, isGote: false },
  { kanji: '香', col: 9, row: 9, isGote: false },
  { kanji: '桂', col: 8, row: 9, isGote: false },
  { kanji: '金', col: 6, row: 9, isGote: false },
  { kanji: '金', col: 4, row: 9, isGote: false },
  { kanji: '桂', col: 2, row: 9, isGote: false },
  { kanji: '香', col: 1, row: 9, isGote: false },
]

const MINO_GUIDE_PIECES: PiecePosition[] = [
  ...GOTE_STANDARD,
  { kanji: '歩', col: 9, row: 7, isGote: false },
  { kanji: '歩', col: 5, row: 7, isGote: false },
  { kanji: '歩', col: 4, row: 7, isGote: false },
  { kanji: '角', col: 3, row: 7, isGote: false },
  { kanji: '歩', col: 2, row: 7, isGote: false },
  { kanji: '歩', col: 1, row: 7, isGote: false },
  { kanji: '飛', col: 9, row: 8, isGote: false },
  { kanji: '玉', col: 8, row: 8, isGote: false },
  { kanji: '金', col: 6, row: 8, isGote: false },
  { kanji: '香', col: 9, row: 9, isGote: false },
  { kanji: '桂', col: 8, row: 9, isGote: false },
  { kanji: '銀', col: 7, row: 9, isGote: false },
  { kanji: '金', col: 4, row: 9, isGote: false },
  { kanji: '桂', col: 2, row: 9, isGote: false },
  { kanji: '香', col: 1, row: 9, isGote: false },
]

const MINO_TEST_PIECES: PiecePosition[] = [
  { kanji: '玉', col: 5, row: 1, isGote: true },
  { kanji: '金', col: 4, row: 1, isGote: true },
  { kanji: '金', col: 6, row: 1, isGote: true },
  { kanji: '銀', col: 3, row: 2, isGote: true },
  { kanji: '飛', col: 3, row: 3, isGote: true },
  { kanji: '角', col: 7, row: 4, isGote: true },
  { kanji: '歩', col: 9, row: 3, isGote: true },
  { kanji: '歩', col: 8, row: 3, isGote: true },
  { kanji: '歩', col: 5, row: 3, isGote: true },
  { kanji: '歩', col: 4, row: 4, isGote: true },
  { kanji: '歩', col: 2, row: 3, isGote: true },
  { kanji: '歩', col: 1, row: 3, isGote: true },
  { kanji: '歩', col: 9, row: 7, isGote: false },
  { kanji: '歩', col: 8, row: 6, isGote: false },
  { kanji: '銀', col: 6, row: 7, isGote: false },
  { kanji: '歩', col: 4, row: 7, isGote: false },
  { kanji: '歩', col: 2, row: 7, isGote: false },
  { kanji: '歩', col: 1, row: 7, isGote: false },
  { kanji: '飛', col: 4, row: 8, isGote: false },
  { kanji: '玉', col: 8, row: 8, isGote: false },
  { kanji: '金', col: 7, row: 8, isGote: false },
  { kanji: '金', col: 5, row: 8, isGote: false },
  { kanji: '香', col: 9, row: 9, isGote: false },
  { kanji: '桂', col: 8, row: 9, isGote: false },
  { kanji: '金', col: 6, row: 9, isGote: false },
  { kanji: '桂', col: 2, row: 9, isGote: false },
  { kanji: '香', col: 1, row: 9, isGote: false },
]

const SIMPLE_CASTLE_PIECES = (kingCol: number, goldCol: number, silverCol: number, rookCol: number): PiecePosition[] => [
  ...GOTE_STANDARD,
  { kanji: '歩', col: 9, row: 7, isGote: false },
  { kanji: '銀', col: silverCol, row: 7, isGote: false },
  { kanji: '歩', col: 5, row: 7, isGote: false },
  { kanji: '歩', col: 4, row: 7, isGote: false },
  { kanji: '歩', col: 2, row: 7, isGote: false },
  { kanji: '歩', col: 1, row: 7, isGote: false },
  { kanji: '飛', col: rookCol, row: 8, isGote: false },
  { kanji: '玉', col: kingCol, row: 8, isGote: false },
  { kanji: '金', col: goldCol, row: 8, isGote: false },
  { kanji: '香', col: 9, row: 9, isGote: false },
  { kanji: '桂', col: 8, row: 9, isGote: false },
  { kanji: '金', col: 6, row: 9, isGote: false },
  { kanji: '桂', col: 2, row: 9, isGote: false },
  { kanji: '香', col: 1, row: 9, isGote: false },
]

// 矢倉 pieces (居飛車, king goes right)
const YAGURA_PIECES: PiecePosition[] = [
  ...GOTE_STANDARD,
  { kanji: '歩', col: 9, row: 7, isGote: false },
  { kanji: '銀', col: 7, row: 7, isGote: false },
  { kanji: '銀', col: 6, row: 7, isGote: false },
  { kanji: '歩', col: 5, row: 7, isGote: false },
  { kanji: '歩', col: 4, row: 7, isGote: false },
  { kanji: '歩', col: 2, row: 7, isGote: false },
  { kanji: '歩', col: 1, row: 7, isGote: false },
  { kanji: '角', col: 8, row: 8, isGote: false },
  { kanji: '玉', col: 6, row: 8, isGote: false },
  { kanji: '金', col: 7, row: 8, isGote: false },
  { kanji: '金', col: 5, row: 8, isGote: false },
  { kanji: '香', col: 9, row: 9, isGote: false },
  { kanji: '桂', col: 8, row: 9, isGote: false },
  { kanji: '飛', col: 2, row: 8, isGote: false },
  { kanji: '桂', col: 2, row: 9, isGote: false },
  { kanji: '香', col: 1, row: 9, isGote: false },
]

export const CASTLES: Castle[] = [
  {
    id: 'mino',
    name: '美濃囲い',
    type: 'furibisha',
    difficulty: 'easy',
    tags: ['居飛車向き'],
    description: [
      'バランスが良く扱いやすい',
      '受けが強く持久戦に強い',
      '初心者におすすめの基本形',
    ],
    features: [
      'バランスが良く扱いやすい',
      '受けが強く持久戦に強い',
      '初心者におすすめの基本形',
    ],
    weaknesses: [
      '端を攻められると弱い',
      '急戦にはやや弱い',
      '攻めがやや受け身になりやすい',
    ],
    recommendedAgainst: '居飛車党全般に有効\n特に振り飛車に強い',
    basicSteps: [
      '▲7六歩',
      '▲4六銀',
      '▲3七八金',
      '▲4六七銀',
      '▲5八玉',
      '▲4六銀',
    ],
    pieces: MINO_PIECES,
    guidePieces: MINO_GUIDE_PIECES,
    guideHighlight: { col: 7, row: 8 },
    guideNextMove: '▲7八銀',
    guideStep: [6, 10],
    guideProgress: 60,
    testPieces: MINO_TEST_PIECES,
    testScore: 85,
    testMessage: 'あと少しで完成！',
    testGoodPoints: [
      '玉の囲いを完成に近い',
      '金銀の配置が良い',
      '左辺の受けが整っている',
    ],
    testFixPoints: [
      '右銀を六にあがろう',
      '飛車の位置が課題',
      '桂馬の活用を考えよう',
    ],
  },
  {
    id: 'takamino',
    name: '高美濃',
    type: 'furibisha',
    difficulty: 'medium',
    tags: ['居飛車向き'],
    description: [
      '美濃囲いをさらに発展させた形',
      '玉の囲いがより堅固',
      'しっかり捌きたい人に向く',
    ],
    features: ['美濃囲いよりさらに堅い', '端攻めへの耐性が高い', '持久戦に強い'],
    weaknesses: ['組むのに手数がかかる', '急戦に対応しにくい'],
    recommendedAgainst: '持久戦志向の居飛車党',
    basicSteps: ['▲7六歩', '▲6八玉', '▲7八玉', '▲8八玉', '▲7八銀', '▲7七銀'],
    pieces: SIMPLE_CASTLE_PIECES(8, 7, 7, 9),
    guidePieces: SIMPLE_CASTLE_PIECES(8, 6, 7, 9),
    guideHighlight: { col: 7, row: 8 },
    guideNextMove: '▲7八銀',
    guideStep: [5, 8],
    guideProgress: 62,
    testPieces: MINO_TEST_PIECES,
    testScore: 80,
    testMessage: 'もう少し！',
    testGoodPoints: ['玉の位置が正しい', '金の配置が良い'],
    testFixPoints: ['銀をもう一段上げよう'],
  },
  {
    id: 'ginkan',
    name: '銀冠',
    type: 'ibisha',
    difficulty: 'medium',
    tags: ['居飛車向き'],
    description: [
      '銀で玉を囲うコンパクトな囲い',
      '攻守のバランスが良い',
      '急戦にも対応しやすい',
    ],
    features: ['攻守バランスが良い', '組みやすい', '相手を選ばない'],
    weaknesses: ['銀が守りに固定される', '端攻めが有効'],
    recommendedAgainst: '居飛車・振り飛車どちらにも',
    basicSteps: ['▲7六歩', '▲6八銀', '▲5七銀', '▲4八玉', '▲3八玉', '▲2八玉'],
    pieces: SIMPLE_CASTLE_PIECES(7, 6, 6, 9),
    guidePieces: SIMPLE_CASTLE_PIECES(7, 7, 6, 9),
    guideHighlight: { col: 6, row: 8 },
    guideNextMove: '▲6八銀',
    guideStep: [4, 8],
    guideProgress: 50,
    testPieces: MINO_TEST_PIECES,
    testScore: 75,
    testMessage: 'あともう一息！',
    testGoodPoints: ['銀の位置が合っている'],
    testFixPoints: ['玉をもう少し右に', '金の配置を調整'],
  },
  {
    id: 'yagura',
    name: '矢倉囲い',
    type: 'ibisha',
    difficulty: 'hard',
    tags: ['居飛車向き'],
    description: [
      '居飛車の最も堅い囲いの一つ',
      '高段者で高い採用率',
      '囲いの理解が重要',
    ],
    features: ['非常に堅固', '持久戦に圧倒的に強い', '金銀4枚の強固な守り'],
    weaknesses: ['組むのに多くの手数', '急戦に崩されることも'],
    recommendedAgainst: '相居飛車（矢倉戦）',
    basicSteps: ['▲7六歩', '▲6八銀', '▲7七銀', '▲6九玉', '▲7九玉', '▲6八金'],
    pieces: YAGURA_PIECES,
    guidePieces: SIMPLE_CASTLE_PIECES(6, 7, 7, 2),
    guideHighlight: { col: 6, row: 8 },
    guideNextMove: '▲6八玉',
    guideStep: [7, 12],
    guideProgress: 58,
    testPieces: MINO_TEST_PIECES,
    testScore: 70,
    testMessage: 'もう少し頑張ろう！',
    testGoodPoints: ['銀の配置が正しい'],
    testFixPoints: ['玉をさらに移動', '金を上に上げよう', '角の使い方を工夫'],
  },
  {
    id: 'fune',
    name: '舟囲い',
    type: 'ibisha',
    difficulty: 'medium',
    tags: ['居飛車向き'],
    description: [
      '玉を守る囲みのない囲い',
      '相手の攻めに合わせやすい',
      '六角の駒の展開を抑える',
    ],
    features: ['素早く組める', '攻撃的な構え', '柔軟な対応が可能'],
    weaknesses: ['守りが薄い', '持久戦には向かない'],
    recommendedAgainst: '速攻志向の相手',
    basicSteps: ['▲7六歩', '▲6八玉', '▲7八玉', '▲5八金右', '▲4八銀', '▲3八銀'],
    pieces: SIMPLE_CASTLE_PIECES(7, 6, 7, 2),
    guidePieces: SIMPLE_CASTLE_PIECES(7, 7, 7, 2),
    guideHighlight: { col: 6, row: 8 },
    guideNextMove: '▲6八金',
    guideStep: [3, 7],
    guideProgress: 43,
    testPieces: MINO_TEST_PIECES,
    testScore: 78,
    testMessage: 'いい感じ！',
    testGoodPoints: ['玉の位置が正しい'],
    testFixPoints: ['金をもう少し上に'],
  },
  {
    id: 'ibisha-anaguma',
    name: '居飛車穴熊',
    type: 'ibisha',
    difficulty: 'hard',
    tags: ['居飛車向き'],
    description: [
      '最も堅固な囲いの一つ',
      '守りを固めて攻撃を狙う',
      '上級者向けの戦法',
    ],
    features: ['圧倒的な堅さ', '持久戦最強クラス', '玉が安全'],
    weaknesses: ['組むのが難しい', '攻めへの転換に手数', '端攻めに注意'],
    recommendedAgainst: '振り飛車党（対振り飛車で多用）',
    basicSteps: ['▲7六歩', '▲6八玉', '▲7八玉', '▲8八玉', '▲9八玉', '▲8八銀'],
    pieces: SIMPLE_CASTLE_PIECES(9, 8, 8, 2),
    guidePieces: SIMPLE_CASTLE_PIECES(9, 9, 8, 2),
    guideHighlight: { col: 9, row: 8 },
    guideNextMove: '▲9八玉',
    guideStep: [8, 14],
    guideProgress: 57,
    testPieces: MINO_TEST_PIECES,
    testScore: 72,
    testMessage: 'あともう少し！',
    testGoodPoints: ['金銀の形が良い'],
    testFixPoints: ['玉をもっと端に', '上部補強が必要'],
  },
  {
    id: 'furibisha-anaguma',
    name: '振り飛車穴熊',
    type: 'furibisha',
    difficulty: 'hard',
    tags: ['振り飛車向き'],
    description: [
      '振り飛車の最強囲い',
      '玉を遠く囲って戦う',
      '受けの強さは抜群',
    ],
    features: ['振り飛車最強の守り', '長期戦で力を発揮', '相手に主導権を与えない'],
    weaknesses: ['組むのが長い', '端攻めを食らいやすい', '攻めの駒が使いにくい'],
    recommendedAgainst: '居飛車党（相穴熊も含む）',
    basicSteps: ['▲7六歩', '▲7八飛', '▲6八銀', '▲5八金', '▲4八玉', '▲3八玉'],
    pieces: SIMPLE_CASTLE_PIECES(1, 2, 2, 7),
    guidePieces: SIMPLE_CASTLE_PIECES(1, 1, 2, 7),
    guideHighlight: { col: 1, row: 8 },
    guideNextMove: '▲1八玉',
    guideStep: [6, 12],
    guideProgress: 50,
    testPieces: MINO_TEST_PIECES,
    testScore: 68,
    testMessage: 'もう少し頑張ろう！',
    testGoodPoints: ['飛車の位置が良い'],
    testFixPoints: ['玉をもっと端に移動', '銀金の配置を整えよう'],
  },
]

export function getCastle(id: string): Castle | undefined {
  return CASTLES.find(c => c.id === id)
}
